import type { Opportunity } from "@/lib/api-types";

import { MOCK_TENANT_ID } from "./users";

export const MOCK_OPPORTUNITIES = [
  {
    id: "DEAL-101",
    tenantId: MOCK_TENANT_ID,
    clientId: "cli-romashka",
    primaryContactId: "ctc-ivanov",
    ownerUserId: "usr-ivanova",
    projectTypeId: "ptype-crm",
    stageId: "qual",
    clientName: "ООО «Ромашка»",
    contactName: "Алексей Иванов",
    title: "Внедрение CRM",
    projectType: "CRM внедрение",
    description: "Discovery и внедрение CRM для финансового и коммерческого блока.",
    plannedStart: "2026-06-01T00:00:00.000Z",
    plannedFinish: "2026-08-15T00:00:00.000Z",
    contractValue: 890000,
    plannedHourlyRate: 5000,
    plannedHours: 178,
    probability: 72,
    status: "new",
    templateId: "tpl-crm",
    feasibilityStatus: "feasible_with_risk",
    feasibilityResult: { overloadedPositions: ["pos-dev"], riskScore: 24 },
    feasibilityCheckedAt: "2026-05-22T12:00:00.000Z",
    createdAt: "2026-05-10T09:00:00.000Z",
    updatedAt: "2026-05-22T12:00:00.000Z",
    demand: [
      { positionId: "pos-pm", requiredHours: 56 },
      { positionId: "pos-dev", requiredHours: 96 },
      { positionId: "pos-design", requiredHours: 26 }
    ],
    customFieldValues: { opportunity_source: "Рекомендация" }
  },
  {
    id: "DEAL-102",
    tenantId: MOCK_TENANT_ID,
    clientId: "cli-techno",
    primaryContactId: "ctc-petrova",
    ownerUserId: "usr-petrov",
    projectTypeId: "ptype-analytics",
    stageId: "proposal",
    clientName: "АО «Техно»",
    contactName: "Мария Петрова",
    title: "DataHub KPI",
    projectType: "Аналитика и KPI",
    description: "Единый контур KPI и контрольных сигналов для проектного портфеля.",
    plannedStart: "2026-06-10T00:00:00.000Z",
    plannedFinish: "2026-09-20T00:00:00.000Z",
    contractValue: 1240000,
    plannedHourlyRate: 6200,
    plannedHours: 200,
    probability: 64,
    status: "new",
    templateId: "tpl-crm",
    feasibilityStatus: "feasible",
    feasibilityResult: { overloadedPositions: [], riskScore: 12 },
    feasibilityCheckedAt: "2026-05-21T11:00:00.000Z",
    createdAt: "2026-05-08T09:00:00.000Z",
    updatedAt: "2026-05-21T11:00:00.000Z",
    demand: [
      { positionId: "pos-pm", requiredHours: 44 },
      { positionId: "pos-arch", requiredHours: 72 },
      { positionId: "pos-dev", requiredHours: 84 }
    ],
    customFieldValues: { opportunity_source: "Партнер" }
  },
  {
    id: "DEAL-103",
    tenantId: MOCK_TENANT_ID,
    clientId: "cli-acme",
    primaryContactId: "ctc-kim",
    ownerUserId: "usr-kozlova",
    projectTypeId: "ptype-audit",
    stageId: "lead",
    clientName: "ACME Studio",
    contactName: "Анна Ким",
    title: "Аудит Salesforce",
    projectType: "Аудит процессов",
    description: "Быстрый аудит текущего Salesforce и карта улучшений.",
    plannedStart: "2026-06-03T00:00:00.000Z",
    plannedFinish: "2026-06-28T00:00:00.000Z",
    contractValue: 320000,
    plannedHourlyRate: 4000,
    plannedHours: 80,
    probability: 42,
    status: "new",
    templateId: "tpl-audit",
    feasibilityStatus: null,
    feasibilityResult: null,
    feasibilityCheckedAt: null,
    createdAt: "2026-05-07T09:00:00.000Z",
    updatedAt: "2026-05-19T11:00:00.000Z",
    demand: [
      { positionId: "pos-pm", requiredHours: 24 },
      { positionId: "pos-arch", requiredHours: 32 }
    ],
    customFieldValues: { opportunity_source: "Сайт" }
  },
  {
    id: "DEAL-104",
    tenantId: MOCK_TENANT_ID,
    clientId: "cli-romashka",
    primaryContactId: "ctc-ivanov",
    ownerUserId: "usr-ivanova",
    projectTypeId: "ptype-crm",
    stageId: "deal",
    clientName: "ООО «Ромашка»",
    contactName: "Алексей Иванов",
    title: "Продление · 2027",
    projectType: "CRM внедрение",
    description: "Продление сопровождения и развитие CRM на следующий год.",
    plannedStart: "2027-01-10T00:00:00.000Z",
    plannedFinish: "2027-12-20T00:00:00.000Z",
    contractValue: 2100000,
    plannedHourlyRate: 7000,
    plannedHours: 300,
    probability: 81,
    status: "new",
    templateId: "tpl-crm",
    feasibilityStatus: "feasible",
    feasibilityResult: { overloadedPositions: [], riskScore: 8 },
    feasibilityCheckedAt: "2026-05-20T12:00:00.000Z",
    createdAt: "2026-05-06T09:00:00.000Z",
    updatedAt: "2026-05-20T12:00:00.000Z",
    demand: [
      { positionId: "pos-pm", requiredHours: 60 },
      { positionId: "pos-dev", requiredHours: 240 }
    ],
    customFieldValues: { opportunity_source: "Account expansion" }
  }
] satisfies Opportunity[];
