import { createAccessProfile } from "@kiss-pm/access-control";

export const tenantAdminProfile = createAccessProfile({
  id: "tenant-admin",
  permissions: [
    "tenant.users.read",
    "tenant.users.manage",
    "tenant.access_profiles.read",
    "tenant.access_profiles.manage",
    "tenant.positions.read",
    "tenant.positions.manage",
    "tenant.workspace_config.read",
    "tenant.workspace_config.manage",
    "tenant.absences.read",
    "tenant.absences.manage",
    "tenant.clients.read",
    "tenant.clients.manage",
    "tenant.contacts.read",
    "tenant.contacts.manage",
    "tenant.products.read",
    "tenant.products.manage",
    "tenant.project_types.read",
    "tenant.project_types.manage",
    "tenant.deal_stages.read",
    "tenant.deal_stages.manage",
    "tenant.opportunities.read",
    "tenant.opportunities.manage",
    "tenant.projects.read",
    "tenant.projects.manage",
    "tenant.project_activation.manage",
    "tenant.project_plan.read",
    "tenant.project_plan.manage",
    "tenant.project_baselines.manage",
    "tenant.project_resources.read",
    "tenant.project_resources.manage",
    "tenant.planning_scenarios.preview",
    "tenant.planning_scenarios.apply",
    "tenant.resource_feasibility.read",
    "profile.read",
    "profile.update",
    "workspace.theme.manage",
    "tenant.audit_events.read"
  ]
});
